namespace MMXOnline;



public enum NewWeaponIds {
	MegaCrush = 200,
	ForceNovaStrike,
	EnemyTracer,
	Gadoken,
	GangarunLauncher,
	VileCore,
	VileRideCore,
	VileWeaponSystem,
	vileSharpnel = 248,
	GreenSpinner,
}

public enum NewProjIds {
	VileSharpnel = 1000,
	SelfDmg = 1100,
	FireWaveWater,
	FireWaveWaterCharged,
	MegaCrush,
	MegaCrushOverclock,
	ForceNovaStrike,
	MegaCrushPull,
	EnemyTracer,
	EnemyTracerOverclock,
	Gadoken,
	GadokenOverclock,
	Koryuken,
	BusterXtr2,
	BusterStockProj,
	BusterForcePlasmaProj,
	BusterForcePlasmaHit,
	X3Saber,
	ZSaberSpin,
	AwakenedZeroSaber,
	ZBuster1k,
	ZBuster2k,
	ZBuster3k,
	MaverickZeroRock,
	VoltTornadoMK2,
	DoubleBullet,
	CurseBullet,
	SpreadShot,
	VileMK2GrabDrain,
	RideStomp,
	GatorStomp,
	SnowRiderProj,
	HeadGunnerMissile,
	InfinityGig,
	GreenSpinnerProj,
	GreenSpinnerCharged,
	GreenSpinnerExplosion,
	MBeamExplosion,
	MBeamPilar,
	MBeamRay,
	MBeamSonicBeam,
	MBeamSonicBeamSplit,
	LOctopusGrenade,
	LOctopusGrenadePart,
	GreenSpinnerCharged2,
	GreenSpinnerChargedProj,
}