namespace MMXOnline;

// Higher values are drawn above
public class ZIndex {
	public const long Default = 0;
	public const long Actor = -500000;
	public const long MainPlayer = -1000000;
	public const long Character = -2000000;
	public const long Background = -3000000;
	public const long Backwall = -4000000;
	public const long Parallax = -5000000;
	public const long Foreground = 2000000;
	public const long HUD = 1000000;
	public const long AboveFont = 2000000;
}

public enum Alignment {
	Left,
	Center,
	Right
}

public enum VAlignment {
	Top,
	Center,
	Bottom
}

// Clamping movement outside map bounds
public enum MoveClampMode {
	None,
	InnerBox,
	OuterBox
}

// Text Categories
public enum TCat {
	Default,
	Option,
	OptionNoSplit,
	Title,
	HUD,
	HUDColored,
	HUDBig,
	BotHelp,
	Chat,
	Custom,
}

public enum WeaponIds {
	// DO NOT change the order of these X weapons
	Buster,
	HomingTorpedo,
	ChameleonSting,
	RollingShield,
	FireWave,
	StormTornado,
	ElectricSpark,
	BoomerangCutter,
	ShotgunIce,
	CrystalHunter,
	BubbleSplash,
	SilkShot,
	SpinWheel,
	SonicSlicer,
	StrikeChain,
	MagnetMine,
	SpeedBurner,
	AcidBurst,
	ParasiticBomb,
	TriadThunder,
	SpinningBlade,
	RaySplasher,
	GravityWell,
	FrostShield,
	TornadoFang,

	LightningWeb,
	FrostTower,
	SoulBody,
	RisingFire,
	GroundHunter,
	AimingLaser,
	DoubleCyclone,
	TwinSlasher,
	// Other stuff whose order does not matter.
	XSaber,
	GigaCrush,
	ItemTracer,
	HyperCharge,
	Hadouken,
	Shoryuken,
	LightHelmetHeadbutt,
	LightUPGrab,
	UPPunch,
	UPParry,
	NovaStrike,
	X6Saber,
	RagingChargeBuster,

	// DO NOT CHANGE THE ORDER OF THESE SIGMA WEAPONS
	Sigma,
	// X1 Summons.
	LaunchOctopus,
	StingChameleon,
	ArmoredArmadillo,
	FlameMammoth,
	StormEagle,
	SparkMandrill,
	BoomerangKuwanger,
	ChillPenguin,
	Velguarder,
	// X2 Summons.
	CrystalSnail,
	BubbleCrab,
	MorphMoth,
	WheelGator,
	OverdriveOstrich,
	WireSponge,
	MagnaCentipede,
	FlameStag,
	FakeZero,
	// X3 Summons.
	ToxicSeahorse,
	BlastHornet,
	VoltCatfish,
	CrushCrawfish,
	NeonTiger,
	GravityBeetle,
	BlizzardBuffalo,
	TunnelRhino,
	DrDoppler,
	// Sigma summons end here.

	// Zero stuff.
	ZSaber,
	ZSaberProjSwing,
	PunchyZSaberProjSwing,

	Raijingeki,
	Raijingeki2,
	Ryuenjin,
	Hyouretsuzan,
	Rakukojin,
	QuakeBlazer,
	Rakuhouha,
	Rekkoha,
	Messenkou,
	Shippuuga,
	EBlade,
	Rising,
	Gemnu,
	ShinMessenkou,
	Shingetsurin,
	AwakenedAura,
	Suiretsusen,
	TBreaker,
	FSplasher,
	Hyoroga,
	Kuuenzan,
	KKnuckle,
	KKnuckleParry,
	ZeroShoryuken,
	MegaPunchWeapon,
	DropKick,
	DarkHold,
	MechGenericWeapon,
	MechMenuWeapon,
	MechBuster,
	MechPunch,
	MechKangarooPunch,
	MechGoliathPunch,
	MechDevilBearPunch,
	MechGoliathStomp,
	MechStomp,
	MechKangarooStomp,
	MechHawkStomp,
	MechFrogStomp,
	MechDevilBearStomp,
	MechChainCharge,
	MechChain,
	MechMissile,
	MechTorpedo,
	ElectricShock,
	MK2StunShot,
	Vulcan,
	RocketPunch,
	FrontRunner,
	VileBomb,
	VileEBomb,
	Napalm,
	VileCutter,
	VileLaser,
	VileMK2Grab,
	NecroBurst,
	RisingSpecter,
	VileFlamethrower,
	StraightNightmare,
	HexaInvolute,

	AxlBullet,
	BlastLauncher,
	RayGun,
	DoubleBullet,
	AssassinBullet,
	Undisguise,
	BlackArrow,
	SpiralMagnum,
	BoundBlaster,
	PlasmaGun,
	IceGattling,
	FlameBurner,
	MetteurCrash,
	BeastHunter,
	MachineBullets,
	RevolverBarrel,
	AncientGun,

	SigmaSlash,
	SigmaBall,
	SigmaWolfHead,
	SigmaWolfHand,
	SigmaWolfHandBeam,
	ChillPIceShot,
	ChillPIceBlow,
	ChillPIcePenguin,
	ChillPBlizzard,
	ChillPSlide,
	SparkMPunch,
	SparkMStomp,
	SparkMSpark,
	ArmoredARoll,
	ArmoredAChargeRelease,
	ArmoredAProj,
	LaunchOMissile,
	LaunchOMelee,
	LaunchOHomingTorpedo,
	LaunchOWhirlpool,
	LaunchODrain,
	BoomerangKBoomerang,
	BoomerangKDeadLift,
	StingCSting,
	StingCTongue,
	StingCSpike,
	StormETornado,
	StormEDive,
	StormEBird,
	StormEGust,
	StormEEgg,
	FlameMFireball,
	FlameMStomp,
	FlameMOil,
	FlameMOilFire,
	VelGFire,
	VelGIce,
	VelGMelee,
	Sigma2Claw,
	Sigma2Ball,
	Sigma2Ball2,
	Sigma2ViralTackle,
	Sigma2ViralBeam,
	Sigma2Mechaniloid,
	ChillPGeneric,
	SparkMGeneric,
	ArmoredAGeneric,
	LaunchOGeneric,
	BoomerangKGeneric,
	StingCGeneric,
	StormEGeneric,
	FlameMGeneric,
	VelGGeneric,
	WSpongeGeneric,
	WSpongeStrikeChain,
	WheelGGeneric,
	WheelGSpinWeapon,
	WheelGEatWeapon,
	WheelGFallWeapon,
	WheelGGrabWeapon,
	BCrabGeneric,
	FStagGeneric,
	MorphMCGeneric,
	MorphMGeneric,
	MagnaCGeneric,
	CSnailGeneric,
	OverdriveOGeneric,
	FakeZeroGeneric,
	BBuffaloGeneric,
	TSeahorseGeneric,
	TunnelRGeneric,
	VoltCGeneric,
	CrushCGeneric,
	NeonTGeneric,
	GBeetleGeneric,
	BHornetGeneric,
	DrDopplerGeneric,
	Sigma3Shield,
	Sigma3Fire,
	Sigma3KaiserMissile,
	Sigma3KaiserMine,
	Sigma3KaiserBeam,
	Sigma3KaiserStomp,
	RideChaserGun,
	RideChaserHit,
	VileWeaponSystem,
	DNACore = 250,


	// Wcut STuff

	//new Vava Stuff
	TridentLine,
	BigBoy,
	FireMourain,

	IrisCrystal,


	// Zain

	ZainParry,


	// Kurumitos Stuff
	KRMelee,
}

public enum ProjIds {
	Buster,
	Buster2,
	Buster3,
	Buster3Giga,
	Buster3GigaMelee,
	Buster3Max,
	Buster4,
	Buster4Giga,
	Buster4Giga2,
	Buster4Max,
	BusterUnpo,
	BusterX3Proj2,
	BusterX3Plasma,
	BusterX3PlasmaHit,
	Torpedo,
	TorpedoCharged,
	MechTorpedo,
	MechTorpedo2,
	Sting,
	StingDiag,
	RollingShield,
	RollingShieldCharged,
	FireWave,
	FireWaveChargedStart,
	FireWaveCharged,
	Tornado,
	TornadoCharged,
	ElectricSpark,
	ElectricSparkChargedStart,
	ElectricSparkCharged,
	Boomerang,
	BoomerangCharged,
	ShotgunIce,
	ShotgunIceSled,
	ShotgunIceCharged,
	CrystalHunter,
	CrystalHunterDash,
	BubbleSplash,
	BubbleSplashCharged,
	SilkShot,
	SilkShotShrapnel,
	SilkShotChargedLv2,
	SilkShotCharged,
	SpinWheel,
	SpinWheelChargedStart,
	SpinWheelCharged,
	SonicSlicer,
	SonicSlicerStart,
	SonicSlicerCharged,
	StrikeChain,
	StrikeChainCharged,
	MagnetMine,
	MagnetMineCharged,
	SpeedBurner,
	SpeedBurnerWater,
	SpeedBurnerTrail,
	SpeedBurnerCharged,
	SpeedBurnerRecoil,
	AcidBurst,
	AcidBurstSmall,
	AcidBurstCharged,
	AcidBurstPoison,
	ParasiticBomb,
	ParasiticBombExplode,
	ParasiticBombCharged,
	TriadThunder,
	TriadThunderBall,
	TriadThunderBeam,
	TriadThunderCharged,
	TriadThunderQuake,
	SpinningBlade,
	SpinningBladeCharged,
	RaySplasher,
	RaySplasherChargedProj,
	RaySplasherTurret,
	RaySplasherHurtSelf,
	GravityWell,
	GravityWellCharged,
	FrostShield,
	FrostShieldAir,
	FrostShieldGround,
	FrostShieldCharged,
	FrostShieldChargedGrounded,
	FrostShieldChargedPlatform,
	FrostShieldPlatform,
	TornadoFang,
	TornadoFang2,
	TornadoFangCharged,
	GigaCrush,
	ItemTracer,
	HyperBuster,
	Hadouken,
	Shoryuken,
	XSaber,
	XSaberProj,
	Headbutt,
	UPGrab,
	UPPunch,
	UPParryBlock,
	UPParryMelee,
	UPParryProj,
	NovaStrike,
	X6Saber,

	ZBuster,
	ZSaber,
	ZSaber1,
	ZSaber2,
	ZSaber3,
	ZSaberProj,
	ZSaberDash,
	ZSaberCrouch,
	ZSaberAir,
	ZSaberRollingSlash,
	ZSaberLadder,
	ZSaberslide,
	ZSaberProjSwing,
	SwordBlock,
	Ryuenjin,
	Denjin,
	RisingFang,
	Raijingeki,
	Raijingeki2,
	Hyouretsuzan,
	Hyouretsuzan2,
	Rakukojin,
	QuakeBlazer,
	QuakeBlazerFlame,
	Shippuuga,
	Gemnu,
	Rakuhouha,
	Rekkoha,
	CFlasher,
	ShinMessenkou,
	ZBuster2,
	ZBuster3,
	ZBuster4,
	Shingetsurin,
	AwakenedAura,
	FSplasher,
	HyorogaProj,
	HyorogaSwing,
	Suiretsusan,
	SuiretsusanProj,
	TBreaker,
	TBreakerProj,

	ElectricShock,
	SpreadShot,
	MK2StunShot,
	VileMissile,
	PopcornDemon,
	PopcornDemonSplit,
	Vulcan,
	DistanceNeedler,
	BuckshotDance,
	RocketPunch,
	SpoiledBrat,
	InfinityGig,
	MechPunch,
	MechKangarooPunch,
	MechGoliathPunch,
	MechDevilBearPunch,
	MechStomp,
	MechFrogGroundPound,
	MechFrogStompShockwave,
	FrontRunner,
	LongshotGizmo,
	FatBoy,
	MechChain,
	MechMissile,
	MechBuster,
	MechBuster2,
	VileBomb,
	VileBombSplit,
	VileEBombStart,
	VileEBomb,
	PeaceOutRoller,
	PeaceOutRollerSplit,
	RumblingBangGrenade,
	FlameRoundGrenade,
	SplashHitGrenade,
	SplashHitProj,
	RumblingBangProj,
	FlameRoundProj,
	FlameRoundWallProj,
	FlameRoundFlameProj,
	VileMK2Grab,
	VileMK2Grab2,
	newUpGrab,
	NecroBurst,
	NecroBurstShrapnel,
	RisingSpecter,
	StraightNightmare,
	HexaInvolute,
	QuickHomesick,
	ParasiteSword,
	MaroonedTomahawk,
	WildHorseKick,
	SeaDragonRage,
	DragonsWrath,

	AxlBullet,
	MetteurCrash,
	BeastKiller,
	MachineBullets,
	RevolverBarrel,
	AncientGun,
	CopyShot,
	AssassinBullet,
	AssassinBulletQuick,
	AssassinBulletEX,
	BlastLauncherGrenadeProj,
	BlastLauncherMineGrenadeProj,
	BlastLauncherGrenadeSplash,
	GreenSpinner,
	GreenSpinnerSplash,
	RayGun,
	RayGunChargeBeam,
	SplashLaser,
	DoubleBullet,
	BlackArrow,
	BlackArrow2,
	BlackArrowGround,
	WindCutter,
	SpiralMagnum,
	SpiralMagnumScoped,
	SniperMissile,
	SniperMissileBlast,
	BoundBlaster,
	BoundBlasterRadar,
	MovingWheel,
	PlasmaGunProj,
	PlasmaGunBeamProj,
	PlasmaGunBeamProjHyper,
	VoltTornado,
	VoltTornadoHyper,
	IceGattling,
	IceGattlingHeadshot,
	IceGattlingHyper,
	GaeaShield,
	FlameBurner,
	AirBlastProj,
	FlameBurnerHyper,
	CircleBlaze,
	CircleBlazeExplosion,

	SigmaSlash,
	SigmaSwordBlock,
	SigmaBall,
	SigmaWolfHeadFlameProj,
	SigmaWolfHeadBallProj,
	SigmaHand,
	SigmaHandElecBeam,
	ChillPIceShot,
	ChillPIceBlow,
	ChillPIcePenguin,
	ChillPBlizzard,
	ChillPSlide,
	SparkMPunch,
	SparkMStomp,
	SparkMSpark,
	ArmoredAProj,
	ArmoredARoll,
	ArmoredAChargeRelease,
	LaunchOMissle,
	LaunchOTorpedo,
	LaunchOWhirlpool,
	LaunchODrain,
	BoomerangKBoomerang,
	BoomerangKDeadLift,
	StingCSting,
	StingCTongue,
	StingCSpike,
	StormEEgg,
	StormEDive,
	StormETornado,
	StormEGust,
	StormEBird,
	FlameMFireball,
	FlameMStomp,
	FlameMStompShockwave,
	FlameMOil,
	FlameMOilSpill,
	FlameMOilFire,
	VelGFire,
	VelGIce,
	VelGMelee,
	Sigma2Ball,
	Sigma2Ball2,
	Sigma2Claw,
	Sigma2Claw2,
	Sigma2ClawDash,
	Sigma2ClawJump,
	Sigma2UpDownClaw,
	Sigma2ViralTackle,
	Sigma2ViralBeam,
	Sigma2ViralProj,
	Sigma2TankProj,
	Sigma2BirdProj,
	Sigma2HopperDrill,
	Sigma2ViralPossess,
	WSpongeSeed,
	WSpongeSeedAI,
	WSpongeSeedAIStriker,
	WSpongeSpike,
	WSpongeChainSpin,
	WSpongeChain,
	WSpongeUpChain,
	WSpongeLightning,
	WheelGSpin,
	WheelGSpinWheel,
	WheelGSpit,
	WheelGBite,
	WheelGEat,
	WheelGGrab,
	WheelGUpBite,
	WheelGStomp,
	BCrabClaw,
	BCrabBubbleSplash,
	BCrabBubbleShield,
	BCrabCrabling,
	BCrabCrablingBubble,
	FStagDashCharge,
	FStagDash,
	FStagDashTrail,
	FStagFireball,
	FStagUppercut,
	MorphMMelee,
	MorphMBeam,
	MorphMPowder,
	MorphMCSpin,
	MorphMCSwing,
	MorphMCThread,
	MorphMCScrap,
	MagnaCMelee,
	MagnaCShuriken,
	MagnaCMagnetMine,
	MagnaCMagnetPull,
	MagnaCTail,
	CSnailMelee,
	CSnailCrystalHunter,
	CSnailSpecial,
	OverdriveOMelee,
	OverdriveOSonicSlicer,
	OverdriveOSonicSlicerUp,
	FakeZeroMelee,
	FakeZeroBuster,
	FakeZeroBuster2,
	FakeZeroBuster3,
	FakeZeroSwordBeam,
	FakeZeroGroundPunch,
	BBuffaloIceProj,
	BBuffaloIceProjAI,
	BBuffaloIceProjAIStriker,

	BBuffaloIceProjGround,
	BBuffaloBeam,
	BBuffaloDrag,
	BBuffaloDash,
	BBuffaloCrash,
	BBuffaloStomp,
	TSeahorseAcid1,
	TSeahorseAcid2,
	TSeahorseAcid3,
	TSeahorsePuddle,
	TSeahorseEmerge,
	TunnelRTornadoFang,
	TunnelRTornadoFang2,
	TunnelRTornadoFangDiag,
	TunnelRDash,
	TunnelRStomp,
	VoltCBall,
	VoltCTriadThunder,
	VoltCSuck,
	VoltCUpBeam,
	VoltCUpBeam2,
	VoltCCharge,
	VoltCBarrier,
	VoltCSparkle,
	VoltCStomp,
	CrushCProj,
	CrushCArmProj,
	CrushCGrab,
	CrushCGrabAttack,
	NeonTRaySplasher,
	NeonTClaw,
	NeonTClaw2,
	NeonTClawAir,
	NeonTClawDash,
	NeonTClawWall,
	NeonTSpecial,
	GBeetleBall,
	GBeetleGravityWell,
	GBeetleLift,
	GBeetleLiftCrash,
	GBeetleStomp,
	BHornetBee,
	BHornetHomingBee,
	BHornetSting,
	BHornetCursor,
	DrDopplerBall,
	DrDopplerBall2,
	DrDopplerDash,
	DrDopplerDashWater,
	DrDopplerAbsorb,
	Sigma3Shield,
	Sigma3ShieldBlock,
	Sigma3Fire,
	Sigma3KaiserMissile,
	Sigma3KaiserMine,
	Sigma3KaiserBeam,
	Sigma3KaiserStomp,
	Sigma3KaiserSuit,
	MaverickContactDamage,
	Burn,
	SigmaVirus,
	RideChaserProj,
	RideChaserHit,
	RideChaserCrash,
	DarkHold,

	// PunchyZeroStuff
	PZeroPunch,
	PZeroPunch2,
	PZeroAirKick,
	PZeroSenpuukyaku, // Spin kick
	PZeroShoryuken, // Air Upercut
	PZeroEnkoukyaku, // Drop Kick
	PZeroYoudantotsu, // Strong Punch
	PZeroParryStart,
	PZeroParryAttack,
	PZeroHadangeki,

	// Dark Zero buster.
	DZBuster,
	DZBuster2,
	DZBuster3,
	DZBuster4,
	DZMelee,
	DZHadangeki,


	// Wcut STuff

	BlockingProjID,

	SigmaViralSlash,
	SigmaSkull,

	GenericWCUTGrabProjID,

	TriggerOldFLinch,

	ForceGrabState,

	// Mavericks stuff wcut

	MammothGrab,

	// Kurumitos Stuff
	KRStandingKick,
	KRAirDunk,
	KROniaki,

	YamiBaraiProj,
	OrochinagiProj,


	// Dynamo
	DynamoBlockSlash,



	HydroStormProj,
	// VAVA (WCUT)
	
	LifeSteal,
	HexaInvoluteProjWC,

	TridentLine,
	BigBoy,
	FireMourain,
	VJab1,
	VJab2,
	RocketPunchWC,
	InfinityGigWC,
	SpoiledBratWC,
	BurensenStart,
	BurensenStomp,
	BurensenEND,
	RagingDemon,
	GizmoGrab,

	VileGrab,
	HexaInvolute2,
	NapalmGrenade,
	LockDownMissileStart,
	LockDownMissileWall,
	VAVA2GRAB,
	VileStomp2,
	VileStomp,
	VileSuperKick,
	TerritorialPowProj,
	EgotisticalPillProj,
	InfinityGigSecond,
	InfinityGigThird,
	SwordBouquetStart,
	SwordBouquetProj,
	BurningDriveProj,
	VileAirRaidStart,
	VileAirRaidPlusKnock,
	BanzaiBeetleProj,
	TwoHeadedSlash,
	MetalCrescent,
	ZipZapperProj,

	// Zain 

	ZainSaberProj,

	ZainPillar,


	// X another
	SiceSlide,

	FlameHadouken,

	// GBD stuff

	GBDKick,
	ShieldBoomerang,
	ShotgunIce2,
	ChainrodProj,


	// Dynamo Stuff

	DynamoCross,
	DynamoAirBuster,
	DynamoAirBuster2,
	DynamoBeam,
	DynamoDropSlash,
	DynamoBoomerangProj,
	DynamoIceDagger,
	DynamoAxeProj,

	DarkHoldD,

	// Extras
	BlockableLaunch,


	BlockableWeak,

		RollingShieldCharged2,


	NormalPush,
	HeavyPush,

	// NEUTRAL ENEMIES

	GunVoltSpark,
	GunVoltTorpedo,

	//Force Busters
	StockBuster,
	PlasmaBuster,
	PlasmaBusterHit,
	PlasmaBuster3,

	// EXtra bonus weapons for X
	RayClaw,

	// X4 Wps

	LightningWebProj,
	LightningWeb,
	LightningWebChargedProj,
	LightningWebCharged,
	FrostTower,
	FrostTowerCharged,
	SoulBodyHologram,
	SoulBodyHologram2,
	SoulBodyX5,
	RisingFire,
	RisingFireChargedStart,
	RisingFireCharged,
	RisingFireUnderwater,
	RisingFireUnderwaterCharged,
	GroundHunter,
	GroundHunterCharged,
	GroundHunterSmall,
	AimingLaser,
	AimingLaserCharged,
	AimingLaserMissle,
	AimingLaserBlade,
	TwinSlasher,
	TwinSlasher2,
	TwinSlasherCharged,
	TwinSlasherCharged2,
	TwinSlasherCharged3,
	TwinSlasherCharged4,
	TwinSlasherCharged5,
	TwinSlasherCharged6,
	TwinSlasherCharged7,
	TwinSlasherCharged8,

	DoubleCyclone,
	DoubleCycloneCharged,

	// Wily Cut Axl.
	BlueBullet,
	AxlMeleeBullet,
	AxlFlashKickProj,
	AxlBulletWC,
	CopyShotWC,
	BlastLauncherWC,
	GreenSpinnerWC,
	IceGattlingWC,
	IceGattlingAltWC,
	RayGunWC,
	SpiralMagnumWC,
	FormicAcidWC,
	FormicAcidSmallWC,
	// Iris Stuff
	IrisFireBallProj,
	IrisCrystal,
	IrisSlashProj,
	IrisStabProj,
	IrisCannon,



	IrisLaserProjDiagonal,
	IrisLaserProjFoward,

	IrisLaserProjUp,
	VirusSlash,
	// Random non-projectiles.
	AxlDiscardedWeapon,

	DragoonSpark,
	HighmaxWallStart,
	HighmaxWall,
	HighmaxHomingProj,
	HighmaxStunShot,
	DesmumeProj1,
	DesmumeProj2,
	DesmumeProj3,
	DesmumeProj4,


	GBDAim,


	// EnemyRPCs (PROJIDS)
	HGM2RPC,
	EnemyWheeler,
	MissileElecSpark,

	// X1 Zero

	RedBuster,


	// Special damage types.
	SelfDmg = 30000,
	SelfTrueDmg,

	// Enviroment effect shenanigans.
	KillZone = 32000,

	// Close to the int16 max value.
	// Do not add things bellow this.
	SelfDestruct = 32700,
}



public enum SlotIndex {
	//X1
	Buster,
	HTorpedo,
	CSting,
	RShield,
	FWave,
	STornado,
	ESpark,
	BCutter,
	SIce,
	Hadouken,
	//X2
	CHunter,
	BSplash,
	SShot,
	SWheel,
	SSlicer,
	SChain,
	MMine,
	SBurner,
	GigaCrush,
	Shoryuken,
	//X3
	ABurst,
	PBomb,
	TThunder,
	SBlade,
	RSplasher,
	GWell,
	FShield,
	TFang,
	HyperCharge,
	//X4
	LWeb,
	FTower,
	SBody,
	RFire,
	GHunter,
	ALaser,
	DCyclone,
	TSlasher,
	NovaStrike,
	//X5
	DHold,
	//extra weapons
	ZSaber = 56,
	//Rides
	BBear = 66,
	Kangroo,
	Hawk,
	Frog,
	Goliath,
	DBear,
	//Mav X1
	CP,
	SMandrill,
	AArmardillo,
	LOctopus,
	BKwagata,
	SChameleon,
	SEagle,
	FMammoth,
	Doggo,
	//Mav X2
	WSponge,
	WGator,
	Carlos,
	FStag,
	MMConcoon,
	MCentiped,
	Dav,
	OOOStrich,
	Claudio,
	//Mav X3
	BBuffalo,
	TSeahorse,
	TRino,
	VCatfish,
	CCrawfish,
	NTiger,
	GBeetle,
	Bhornet,
	DrCatus,
	//moth form
	MMMoth,
	//sigma
	Sigma,
	WSigmaHead,
	WSHand,
	//Sigma Virus
	MechaniloidBird,
	MechaniloidDino,
	MechaniloidFish,
	MechaniloidDrill,
	//DrDoppler Body
	DrDoppler,
	//Axl
	Abullet,
	BLauncher,
	RGun,
	IGattling,
	BArrow,
	FBurner,
	PGun,
	SMagnum,
	BBlaster,
	DrDShock = 121,
	DrDVaccine,
	CPIceStatue
}



//weapon bar index
public enum WeaponBarIndex {
	//X1
	HomingTorpedo,
	ChameleonSting,
	RollingShield,
	FireWave,
	StormTornado,
	ElectricSpark,
	BoomerangCutter,
	ShotgunIce,
	//X2
	CrystalHunter,
	BubbleSplash,
	SilkShot,
	SpinWheel,
	SonicSlicer,
	StrikeChain,
	MagnetMine,
	SpeedBurner,
	GigaCrush,
	//X3
	AcidBurst,
	ParasiticBomb,
	TriadThunder,
	SpinningBlade,
	RaySplasher,
	GravityWell,
	FrostShield,
	TornadoFang,
	HyperCharge,
	ZSaber,
	//X4
	LightningWeb,
	FrostTower,
	SoulBody,
	RisingFire,
	GroundHunter,
	AimingLaser,
	DoubleCyclone,
	TwinSlasher,
	NovaStrike,
	//X5
	DarkHold,
	//AxlWC
	AxlBullet = 64,
	BlastLauncher,
	RayGun,
	IceGattling,
	BlackArrow,
	FlameBurner,
	PlasmaGun,
	SpiralMagnum,
	BoundBlaster,
	//Others
	VileAmmo,
	MaverickAmmo,
	MaverickAmmoOff,
	WeaponAmmo,
	WeaponAmmoOff,
	SuperBar,
	SuperBarOff,
	ZainCounter,

	LastIndex
}

public enum CharHpBarIndex{
	X,
	XAnother,
	ZeroX1,
	ZeroX2,
	ZeroX6,
	Vile,
	AxlWC,
	AxlX8,
	Sigma,
	Doppler,
	GBD,
	Dynamo,
	Dragoon,
	Zain,
	BlackZero,
	WhiteAxl,
	BoostMode,
	SoulBody,
	Iris
}

public enum VehicleHpBarIndex {
	BlackBear,
	Frog,
	Kangroo,
	Hawk,
	Goliath,
	DevilBear,
	RideChaser
}


